// src/routes/(app)/best-unit/+page.svelte
<article>
	<div class="title">Unit 3 Finishes Their Statements</div>
	<p>
		This past Wednesday, Jan 18th, Unit 3 has become the first second unit to complete all of its
		statements for the We the People: The Citizens and the Constitution competition. The achievement
		of this glorious milestone for the second consecutive year further proves the dominant legacy of
		Unit 3, which is this year's recipient of the Unit of the Year Award.
	</p>

	<p>
		“Best unit for real,” Aidan Sprouls '23 said. “The drafts really came a long way.” Talia
		Moskowitz '24 recalls the beginning of the 2022-23 school year: “I was nervous I wouldn't be
		able to join the exclusive Unit 3.” Moskowitz said. “It definitely had a compounding effect when
		Kam sent a second unit choice form.”
	</p>

	<p>
		Unit 3 has faced many trials and tribulation during the drafting process. At one point, they
		even had to read the textbook. Yet, overcoming these obstacles Unit 3 became the first second
		unit to finish all their statements. We were able to speak with Tommy Dry '24 and Ayla Nahmias
		'24 of Unit 3 about the pace with which their statements were completed. “Simply put we're just
		the best unit and that's why we work so well together.” Nahmias said. Tommy agreed with this
		opinion stating the group's “pure genius and adroitness” pushed them into success.
	</p>
</article>

<style lang="scss">
	article {
		font-size: 1.2em;

		width: 60%;
		margin: 1em auto;

		@media screen and (max-width: $mobile-width) {
			width: 85%;
		}

		.title {
			font-size: 1.5em;

			text-align: center;
		}

		p {
			font-family: $font-body;
		}
	}
</style>

// client/src/components/BestUnit.tsx
import '../styles/routes/BestUnit.scss';

export default function BestUnit() {
  return (
    <div className="section best-unit">
      <div className="title">Unit 3 Finishes Its Statements</div>
      <p>
        This past Tuesday, Jan. 11th, Unit 3 has completed all of its statements for the We the People: The Citizens and the Constitution
        competition. This next big milestone further proves the absolute supremacy of Unit 3, which is this year’s recipient of the Unit of
        the Year Award.
      </p>
      <p>“It’s been a long journey,” says Jet Tober of Unit 3. “I’m just so proud of all of the work everyone has done.”</p>
      <p>
        Ryan Salik recalls the beginning of the 2021-2022 school year: “I was, like, so nervous that I wouldn’t be in Unit 3, ‘cause like, I
        always wanted Unit 3 and it was my dream to be in Unit 3.”
      </p>
      <p>
        Unit 3 has faced many trials and tribulations during the drafting process. At one point, they even had to read a book. Yet,
        overcoming these obstacles, Unit 3 became the first 2nd unit to finish all statements.
      </p>
      <p>
        We got to speak with Meredith and Clara of Unit 3 to learn more about their efficiency. Meredith noted, “we just work so well
        together because we’re the best unit. There’s not much to it besides that.”
      </p>
      <p>Clara concurs, stating that the group's “pure talent and skill” is what propelled them to success.</p>
      <p>
        Right now, Unit 3 is benevolent giving readers the chance to claim <strong>their</strong> signed pocket Constitution. Get yours
        today <a href="/unit/3">here</a> (the Official Staples We The People Website may receive compensation for orders placed through its
        affiliate links).
      </p>
    </div>
  );
}
